### ISSUE TITLE
Flip animation name is prefixed, why?

### ISSUE THREAD

**Issue by gremo** [animate-css/animate.css#1152]
https://github.com/animate-css/animate.css/blob/main/source/flippers/flip.css#L31

```css
.animated.flip {
  backface-visibility: visible;
  animation-name: flip;
}
```

Is this something on purpose?

**Comment by eltonmesquita** [comment]
I think this gone through in an old refactor. There's no impact really and theory it is safer, but as we now use a proper class prefix, this isn't necessary. I'd happily merge a PR just for the sake of consistency ;D

**Comment by gremo** [comment]
Yep your right, it works anyways, thanks!

```css
.animate__animated.animate__flip {
  -webkit-backface-visibility: visible;
  backface-visibility: visible;
  -webkit-animation-name: flip;
  animation-name: flip;
}
```

```css
.animate__bounce {
  -webkit-animation-name: bounce;
  animation-name: bounce;
  -webkit-transform-origin: center bottom;
  transform-origin: center bottom;
}
```
