### ISSUE TITLE
animation on Safari(IOS MacOS iPadOS) only flash, and no normal animation. 

### ISSUE THREAD

**Issue by MatchOvO** [animate-css/animate.css#1565]
### Describe The Bug

My css class is:
```css
.loading-box .logo{
    --icon-size: 96px;
    color: #2d2f39;
    animation: flipInX;
    animation-duration: 1s;
}

.loading-box h1{
    font-size: 34px;
    color: #2d2f39;
    animation: flipInX;
    animation-duration: .5s;
    animation-delay: .5s;
    animation-fill-mode: both;
}

.loading-box h3{
    font-size: 16px;
    color: #2d2f39;
    animation: fadeIn;
    animation-duration: .8s;
    animation-delay: .5s;
    animation-fill-mode: both;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}
```

## In Chrome
<img width="1680" alt="截屏2022-06-30 13 29 34" src="https://user-images.githubusercontent.com/108038560/176599988-0e70a13a-abe6-4aad-9e4b-122275a9c3a0.png">

## In Safari
<img width="1680" alt="截屏2022-06-30 13 31 10" src="https://user-images.githubusercontent.com/108038560/176600097-031c6aaa-63b9-4084-894c-54ea0f4cdd08.png">
