### ISSUE TITLE
Animate on Hover?

### ISSUE THREAD

**Issue by blueridgemountains1** [animate-css/animate.css#170]
Animate.css works just fine (great project, btw!)

However, I'm curious about utilizing it to only animate on hover.

I have tried adding a class I thought would work, however it is not.

``` css
.animatedhover:hover {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}
```

``` html
<span class="icon animatedhover bounce"></span>
```

Let it be noted that regular animated class works fine.

``` html
<span class="icon animated bounce"></span>
```
