### ISSUE TITLE
`--animate-delay` has no effect (and I think that I’ve figured out why)

### ISSUE THREAD

**Issue by handcoding** [animate-css/animate.css#1793]
### Describe The Bug

The docs mention that users can add `--animate-delay` to their CSS to delay when a given animation starts. But this CSS variable seems to have no effect. 

![Safari - Animate css  A cross-browser library of CSS animations  - 2024-06 at 11-12-58](https://github.com/animate-css/animate.css/assets/118319/cdc8c506-99bc-4f4b-92af-ce7f277dbc47)

### Steps To Reproduce

1. Run this minimized test case, which includes `--animate-delay: 5s;` on an element:
 https://codepen.io/handcoding/pen/dyEZxoJ 

### Expected Behavior

The expected behavior is that this element would animate _after_ a delay of 5 seconds. 

### Desktop

- OS: macOS Sonoma
- Browser: Safari and Chrome and Firefox (that I’ve tested so far)
- version: animate.css 4.1.1

### Additional Context

I believe that I’ve figured out why this is happening. 

In [animate.css's](https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.css) base `.animate__animated` class, the library programmatically connects the `animation-duration` CSS property to its variable through `animation-duration: var(--animate-duration);` (which is good!).

.... but then the library’s `.animate__animated` class doesn’t _also_ connect the `animation-delay` CSS property to its corresponding `--animate-delay` variable. 

So the upshot is that if you set, say, `--animate-delay: 5s;` on an element, there ends up being no delay at all.

```css 
@charset "UTF-8";/*!
 * animate.css - https://animate.style/
 * Version - 4.1.1
 * Licensed under the MIT license - http://opensource.org/licenses/MIT
 *
 * Copyright (c) 2020 Animate.css
 */
:root {
  --animate-duration: 1s;
  --animate-delay: 1s;
  --animate-repeat: 1;
}
.animate__animated {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-duration: var(--animate-duration);
  animation-duration: var(--animate-duration);
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

[…]
```

PS I believe that the `--animate-repeat` CSS variable is also affected by this since that doesn’t appear to be programmatically connected to its corresponding CSS property within `.animate__animated` either.
