### ISSUE TITLE
Should .shake move the element only once?

### ISSUE THREAD

**Issue by athyuttamre** [animate-css/animate.css#195]
At the moment, `shake` shakes the element 5 times. This means if the user uses`vendor-animation-iteration-count`, he or she can only shake the element in multiples of 5. Making `shake` shake the element only once would solve this problem and allow the user to define a custom number of shakes.

Here's one suggestion (pardon me if the code isn't of the highest quality):

``` css
@keyframes shake {
  0%, 100% {
    transform: translateX(0);
  }

  33% {
    transform: translateX(-10px);
  }

  67% {
    transform: translateX(10px);
  }
}

.shake {
  animation-name: shake;
}
```
