### ISSUE TITLE
I think for some animations, a complementary style is needed to set the initial transform values

### ISSUE THREAD

**Issue by behrangsa** [animate-css/animate.css#35]
For example, I want to use `bounceInDown`, so that when the user clicks on a link, a div bounces in to the page.

Right now, I have to add this styling to that element, so that it initially does not appear on the page:

``` css
.my-div {
  -webkit-transform: translateY(-2000px);
     -moz-transform: translateY(-2000px);
      -ms-transform: translateY(-2000px);
       -o-transform: translateY(-2000px);
          transform: translateY(-2000px);
}
```

Maybe a style like `bounceInDown-init` is needed:

``` css
.bounceInDown-init {
  -webkit-transform: translateY(-2000px);
     -moz-transform: translateY(-2000px);
      -ms-transform: translateY(-2000px);
       -o-transform: translateY(-2000px);
          transform: translateY(-2000px);
}
```
