### ISSUE TITLE
delay classes - feature/addition

### ISSUE THREAD

**Issue by james2doyle** [animate-css/animate.css#53]
This is more of a feature that I found myself adding. 

``` css
.animated .delay200 {
    animation-delay: 0.2s;
}
```

I wanted this because I am doing a lot of animations on page load and I didn't want to do them in javascript. 

I also didn't want to do:

``` css
.animated {
    animation-delay: 0.2s
}
```

Because I want each animation to have a sequential order. I was figuring there would be some default ones. Anyone else see this as useful? Or do you think it is too specific for what I was doing?
