### ISSUE TITLE
Incorrect vendor prefix in `fadeInDown` from custom build tool

### ISSUE THREAD

**Issue by nizaroni** [animate-css/animate.css#72]
The `fadeInDown` vendor prefix CSS for Opera is being generated with Microsoft vendor prefixes when using the [Web-based custom build tool](http://daneden.me/animate/build/).

``` css
@-o-keyframes fadeInDown {
    0% {
        opacity: 0;
        -ms-transform: translateY(-20px);
    }

    100% {
        opacity: 1;
        -ms-transform: translateY(0);
    }
}
```

I'd be happy to make a pull request if you point me to the website code!
